export const ADD_EXAM_INSTRUCTION = 'ADD_EXAM_INSTRUCTION';
export const EXAM_SAVED = 'EXAM_SAVED';
export const REMOVED_EXAM_SAVED_MODAL = 'REMOVED_EXAM_SAVED_MODAL';

export const OBTAIN_PREVIOUS_EXAM_DETAILS_START =
  'OBTAIN_PREVIOUS_EXAM_DETAILS_START';
export const OBTAIN_PREVIOUS_EXAM_DETAILS = 'OBTAIN_PREVIOUS_EXAM_DETAILS';
export const CLEAR_OBTAIN_PREV_LOADED_TEXT = 'CLEAR_OBTAIN_PREV_LOADED_TEXT';
export const DETAIL_NOT_FOUND_TEXT = 'DETAIL_NOT_FOUND_TEXT';
